"""The pinned read contract for upstream's ``v_*`` views.

A full snapshot of every column of every view this repo may read, taken from
``portfolio-financial-analysis`` ``src/kg_schema/views.py`` (commit 0a528be, 2026-10-05). No
projector reads them yet, so this is wider than what the projection will depend on: trim
each view to the columns the write path actually reads when it lands (T-031). Checked by
``cli/check_view_contract.py`` (T-030): a pinned column that disappears is drift, a column
upstream adds is only a note. Update the pin when upstream changes a view on purpose.
"""

from __future__ import annotations

# View -> columns, in upstream's frozen order.
VIEW_COLUMNS: dict[str, tuple[str, ...]] = {
    "v_score_snapshot": (
        "id",
        "ticker",
        "asset_id",
        "score_type",
        "raw_value",
        "normalized_score",
        "event_time",
        "computed_at",
        "model",
        "inputs_json",
        "filing_id",
        "rating",
        "narrative",
        "strengths_json",
        "risks_json",
        "run_id",
        "run_kind",
        "available_at",
    ),
    "v_analysis_run": (
        "run_id",
        "as_of",
        "code_version",
        "status",
        "started_at",
        "finished_at",
        "universe_size",
        "planned_units",
        "completed_units",
        "skipped_units",
        "failed_units",
        "params_json",
    ),
    "v_pricing_run": (
        "run_id",
        "as_of",
        "code_version",
        "status",
        "started_at",
        "finished_at",
        "universe_size",
        "planned_units",
        "completed_units",
        "skipped_units",
        "failed_units",
        "params_json",
    ),
    "v_quant_run": (
        "run_id",
        "command",
        "as_of",
        "code_version",
        "engine_version",
        "status",
        "started_at",
        "finished_at",
        "error",
        "params_json",
    ),
    "v_cycle_run": (
        "run_id",
        "cycle_type",
        "as_of",
        "code_version",
        "status",
        "started_at",
        "finished_at",
        "params_json",
    ),
    "v_universe_coverage": (
        "id",
        "as_of",
        "universe",
        "symbol",
        "asset_id",
        "in_assets",
        "has_fundamental",
        "has_metrics",
        "has_pricing",
        "has_observations",
        "has_returns",
        "covered",
        "missing_json",
        "checked_at",
        "run_id",
    ),
    "v_sector": (
        "sector_id",
        "sector_name",
        "asset_count",
        "sub_industry_count",
    ),
    "v_industry": (
        "industry_name",
        "sector_name",
        "sector_id",
        "asset_count",
    ),
    "v_price_observation": (
        "id",
        "ticker",
        "asset_id",
        "obs_date",
        "close",
        "prev_close",
        "log_return",
        "true_range",
        "atr_14",
        "realized_vol_21d",
        "realized_vol_90d",
        "max_drawdown_90d",
        "momentum_21d",
        "momentum_63d",
        "momentum_252d",
        "dollar_volume",
        "source",
        "event_time",
        "computed_at",
        "engine_version",
    ),
    "v_sec_filing": (
        "id",
        "ticker",
        "asset_id",
        "form",
        "fiscal_year",
        "fiscal_period",
        "filing_date",
        "accession_number",
        "period_end",
        "retrieved_at",
        "available_at",
    ),
    "v_sec_filing_section": (
        "id",
        "ticker",
        "asset_id",
        "filing_id",
        "form",
        "fiscal_period",
        "section_type",
        "item_number",
        "item_label",
        "heading",
        "ordinal",
        "text",
        "text_sha256",
        "word_count",
        "extraction_method",
        "source_url",
        "event_time",
        "retrieved_at",
        "engine_version",
    ),
    "v_veto": (
        "id",
        "ticker",
        "asset_id",
        "rule_id",
        "severity",
        "raised_on",
        "cleared_on",
        "last_seen_on",
        "detected_at",
        "cleared_at",
        "evidence_json",
        "run_id",
    ),
    "v_data_quality_issue": (
        "id",
        "ticker",
        "asset_id",
        "filing_id",
        "form",
        "fiscal_period",
        "period_end",
        "metric_group",
        "metric_name",
        "metric_engine_version",
        "rule_id",
        "severity",
        "quarantined",
        "value",
        "evidence_json",
        "gate_version",
        "created_at",
        "run_id",
    ),
    "v_rule_catalog": (
        "rule_id",
        "description",
        "severity",
        "enabled",
        "params_json",
        "param_metric",
        "param_operator",
        "param_threshold",
        "created_at",
    ),
    "v_portfolio_position": (
        "id",
        "ticker",
        "asset_id",
        "valid_from",
        "valid_to",
        "weight",
        "cost_basis",
        "opened_by_cycle",
        "run_id",
    ),
    "v_shared_executive_edge": (
        "asset_id_a",
        "ticker_a",
        "asset_id_b",
        "ticker_b",
        "person_count",
        "total_weight",
        "first_seen",
        "last_seen",
        "method",
    ),
    "v_cycle_ranking": (
        "cycle_run_id",
        "cycle_type",
        "cycle_date",
        "ticker",
        "asset_id",
        "rank",
        "blended_score",
        "components_json",
        "vetoed",
        "veto_rules_json",
        "selected",
        "target_weight",
    ),
    "v_weight_scheme": (
        "cycle_run_id",
        "cycle_type",
        "cycle_date",
        "scheme_id",
        "weights_json",
        "top_n",
        "max_name_weight",
        "max_sector_weight",
        "soft_veto_penalty",
    ),
    "v_weight_component": (
        "cycle_run_id",
        "cycle_type",
        "cycle_date",
        "score_type",
        "weight",
    ),
    "v_sector_aggregate_snapshot": (
        "id",
        "sector_name",
        "sector_id",
        "cycle_date",
        "metric_type",
        "member_count",
        "mean_raw",
        "mean_normalized",
        "computed_at",
        "run_id",
    ),
    "v_corporate_action": (
        "id",
        "ticker",
        "asset_id",
        "action_type",
        "ex_date",
        "value",
        "currency",
        "declared_date",
        "record_date",
        "pay_date",
        "frequency",
        "source",
        "engine_version",
        "ingested_at",
    ),
    "v_quant_return_daily": (
        "id",
        "ticker",
        "asset_id",
        "obs_date",
        "close_split_adj",
        "adj_close",
        "tr_index",
        "cash_dividend",
        "split_factor",
        "price_log_return",
        "tr_log_return",
        "source",
        "engine_version",
        "computed_at",
    ),
    "v_risk_free_rate": (
        "id",
        "curve",
        "rate_date",
        "annualized_rate",
        "source",
        "engine_version",
        "ingested_at",
    ),
    "v_benchmark_series": (
        "id",
        "benchmark",
        "obs_date",
        "level",
        "total_return_level",
        "log_return",
        "source",
        "engine_version",
        "ingested_at",
    ),
    "v_quant_risk_model": (
        "id",
        "as_of",
        "model_version",
        "lookback_days",
        "min_history_days",
        "n_assets",
        "cov_estimator",
        "cov_shrinkage",
        "ret_estimator",
        "periods_per_year",
        "panel_engine_version",
        "panel_spec_json",
        "rf_annual",
        "computed_at",
        "quant_run_id",
        "manifest_json",
    ),
    "v_quant_portfolio": (
        "id",
        "as_of",
        "kind",
        "frontier_k",
        "objective",
        "solver",
        "status",
        "expected_return",
        "expected_vol",
        "sharpe",
        "rf_annual",
        "n_positions",
        "turnover",
        "target_param",
        "model_id",
        "engine_version",
        "computed_at",
        "manifest_json",
    ),
    "v_quant_position": (
        "id",
        "portfolio_id",
        "as_of",
        "kind",
        "ticker",
        "asset_id",
        "weight",
        "valid_from",
        "valid_to",
    ),
    "v_quant_frontier_point": (
        "id",
        "model_id",
        "as_of",
        "k",
        "target_return",
        "expected_return",
        "expected_vol",
        "sharpe",
        "status",
        "weights_json",
        "portfolio_id",
    ),
    "v_quant_benchmark_performance": (
        "id",
        "portfolio_id",
        "as_of",
        "kind",
        "date",
        "realized_return",
        "cumulative_return",
        "benchmark",
        "benchmark_return",
        "active_return",
        "engine_version",
        "computed_at",
    ),
    "v_quant_vs_live": (
        "as_of",
        "kind",
        "ticker",
        "asset_id",
        "benchmark_weight",
        "live_weight",
        "active_weight",
    ),
}

# Upstream views this repo deliberately does not read.
NOT_READ: dict[str, str] = {
    "v_universe_membership": "frozen upstream (agents no longer write it); membership is read point-in-time from universe.db",
}
