"""Entry point: build ``data.ttl`` from universe.db + urls.db/nlp.db.

    python cli/build_data_ttl.py              # full run
    python cli/build_data_ttl.py --limit 500  # smoke test (caps news rows)

Orchestrates :mod:`etl.asset_master` (universe.db -> ``:Asset``/``:classifiedAs``/
``:UniverseMembership``)
and :mod:`etl.news_to_rdf` (urls.db/nlp.db -> ``:NewsArticle``/``:ScoreSnapshot``/
``:RiskEvent``). Scope is news + company/sector structuring only; SEC EDGAR,
pricing, executives, and the summary tables are out of scope for this phase
(see ``etl/README.md``).

The output is a flat Turtle file, NOT partitioned into the named graphs
``07-ontology-topology.md`` designs -- this is a single-shot MVP load, not the
target architecture. It loads AFTER the schema files:
``tbox.ttl`` -> ``shapes.ttl`` -> ``reference.ttl`` -> ``rules.ttl`` -> ``data.ttl``.

rdflib is used below only for a small representative-sample SHACL conformance
check; running ``pyshacl`` over the full multi-million-triple dataset is not a
practical validation step at this row count (see
``etl/common/turtle_util.py``).
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path
from typing import TextIO

import rdflib
from pyshacl import validate as shacl_validate

from etl import asset_master, config, news_to_rdf

_PREFIXES = (
    "@prefix :      <https://thesis.local/kg/portfolio#> .\n"
    "@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .\n"
    "@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\n\n"
)

_HEADER_TEMPLATE = """# Portfolio Knowledge Graph -- data.ttl
# Generated by etl/build_data_ttl.py on {timestamp}
#
# SCOPE: news + company/sector structuring only.
#
# Load order into a fresh triple store (this file LAST):
#   schema/tbox.ttl -> shapes.ttl -> reference.ttl -> rules.ttl -> data.ttl
# data.ttl's :classifiedAs edges reference :Ind_*/:Sec_* individuals declared in
# reference.ttl; :Asset/:NewsArticle/:ScoreSnapshot/:RiskEvent classes and every
# SHACL shape come from tbox.ttl/shapes.ttl.
#
# This is a flat Turtle file -- NOT partitioned into the named graphs
# 07-ontology-topology.md designs. Bitemporal/audit-trail tracking via
# named-graph identity does not apply to data loaded this way; this is a
# single-shot MVP load, not the target architecture.
#
# Excluded this phase (see etl/README.md):
#   - SEC EDGAR filings/sections (:SECFiling, :SECFilingSection)
#   - Pricing/trading data (:PriceObservation)
#   - :Executive -- DEF14A-sourced only per tbox.ttl
#   - article_summary / sector_summary -- the "summary" feature
#   - discovered_urls, article_entities, discovery_progress
#   - Computed/orchestrator-layer classes (:Veto, :AttractivenessSnapshot,
#     :Portfolio, :PortfolioPosition) -- these consume this ETL's output, they
#     are not populated by it. (:Universe/:UniverseMembership ARE populated,
#     from universe.db -- T-100.)
#
# Provisional formulas applied without calibration sign-off (etl/common/severity.py):
#   G1 rawValue = clamp(positive - negative, -1, 1)
#   G2 9-dimension category -> 4-value RiskEvent.category bucket table
#   G3 severity thresholds + hard-trigger keyword bump ladder
#   G9 publishedDate = pub_date, falling back to fetched_at when pub_date is null
"""


def _write_header(out: TextIO) -> None:
    out.write(_HEADER_TEMPLATE.format(timestamp=time.strftime("%Y-%m-%d %H:%M:%S")))
    out.write("\n")


def reference_asset_tickers() -> set[str]:
    """Tickers ``schema/reference.ttl`` already declares as ``:Asset`` individuals.

    :mod:`etl.asset_master` skips re-emitting these so ``reference.ttl`` stays
    the single source of truth for their ``cikNumber`` / ``companyName``.
    """
    ns = rdflib.Namespace("https://thesis.local/kg/portfolio#")
    graph = rdflib.Graph()
    graph.parse(str(config.schema_dir() / "reference.ttl"), format="turtle")
    return {
        str(ticker)
        for subject in graph.subjects(rdflib.RDF.type, ns.Asset)
        for ticker in graph.objects(subject, ns.tickerSymbol)
    }


def generate(
    out_path: Path, news_limit: int | None = None, *, with_header: bool = True
) -> tuple[asset_master.UniverseSummary, dict[str, int], list[str]]:
    """Write a Turtle dataset to ``out_path``. Returns ``(universe, stats, warnings)``."""
    warnings: list[str] = []
    universe_db = config.universe_db_path()
    stints = asset_master.read_stints(universe_db, warnings)
    already_defined = reference_asset_tickers()
    with out_path.open("w", encoding="utf-8") as out:
        if with_header:
            _write_header(out)
        out.write(_PREFIXES)
        universe = asset_master.build_assets(
            stints, out, warnings, already_defined, file_mtime=universe_db.stat().st_mtime
        )
        db_paths = news_to_rdf.NewsDbPaths(
            source=config.urls_db_path(), results=config.results_db_path()
        )
        stats = news_to_rdf.stream_news(db_paths, universe.tickers, out, warnings, limit=news_limit)
    return universe, stats, warnings


def _shacl_check(ttl_path: Path) -> None:
    """Run pyshacl on ``ttl_path`` against the real tbox + shapes + reference."""
    schema_dir = config.schema_dir()
    print(f"Validating {ttl_path.name} against tbox.ttl + shapes.ttl + reference.ttl ...")
    data_graph = rdflib.Graph()
    data_graph.parse(str(ttl_path), format="turtle")
    data_graph.parse(str(schema_dir / "reference.ttl"), format="turtle")

    shapes_graph = rdflib.Graph()
    shapes_graph.parse(str(schema_dir / "tbox.ttl"), format="turtle")
    shapes_graph.parse(str(schema_dir / "shapes.ttl"), format="turtle")

    conforms, _results_graph, results_text = shacl_validate(
        data_graph, shacl_graph=shapes_graph, abort_on_first=False, meta_shacl=False
    )
    print(f"SHACL conforms: {conforms}")
    if not conforms:
        print(results_text)


def _validate_sample() -> None:
    """Build a fresh ``KG_SAMPLE_NEWS_ROWS``-row sample and SHACL-check it."""
    sample_path = config.REPO_ROOT / "src" / "etl" / "_sample_for_validation.ttl"
    print(f"\nBuilding a {config.sample_news_rows()}-row validation sample...")
    generate(sample_path, news_limit=config.sample_news_rows(), with_header=False)
    _shacl_check(sample_path)
    sample_path.unlink(missing_ok=True)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build data.ttl from universe.db + urls.db/nlp.db."
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        metavar="N",
        help="cap news rows read (smoke test); skips the file header and SHACL-checks "
        "the output directly instead of building a separate sample",
    )
    parser.add_argument(
        "--no-validate",
        action="store_true",
        help="skip the post-build SHACL validation step entirely",
    )
    return parser.parse_args()


def main() -> None:
    """CLI entry point."""
    args = _parse_args()
    out_path = config.output_path()
    smoke = args.limit is not None

    t0 = time.time()
    print(
        f"Reading {config.universe_db_path()} (universe) and streaming {config.urls_db_path()} "
        f"(SOURCE) + {config.results_db_path()} (RESULTS) ..."
    )
    universe, stats, warnings = generate(out_path, news_limit=args.limit, with_header=not smoke)
    elapsed = time.time() - t0

    print(f"\n{out_path} written in {elapsed:.1f}s")
    print(
        f"  Assets:         {universe.assets_written} "
        f"(+ {len(universe.tickers) - universe.assets_written} declared in reference.ttl)"
    )
    print(
        f"  Memberships:    {universe.memberships} "
        f"({universe.open_memberships} open, {universe.closed_memberships} closed)"
    )
    print(f"  {universe.freshness_line()}")
    print(f"  NewsArticles:   {stats['articles']}")
    print(f"  ScoreSnapshots: {stats['score_snapshots']}")
    print(f"  RiskEvents:     {stats['risk_events']}")
    if warnings:
        print(f"\n{len(warnings)} warning(s):")
        for warning in warnings:
            print(f"  - {warning}")
    else:
        print("\nNo warnings.")

    if not args.no_validate:
        print()
        if smoke:
            _shacl_check(out_path)
        else:
            _validate_sample()

    print("\nDone.")


if __name__ == "__main__":
    main()
